export const FETCH_DASHBOARD_DATA_SUCCESS = "FETCH_DASHBOARD_DATA_SUCCESS";
export const FETCH_DASHBOARD_DATA_FAIL = "FETCH_DASHBOARD_DATA_FAIL";
export const FETCH_DASHBOARD_DATA_START = "FETCH_DASHBOARD_DATA_START";

export const FETCH_AIRDROP_DASHBOARD_DATA_SUCCESS = "FETCH_AIRDROP_DASHBOARD_DATA_SUCCESS";
export const FETCH_AIRDROP_DASHBOARD_DATA_FAIL = "FETCH_AIRDROP_DASHBOARD_DATA_FAIL";
export const FETCH_AIRDROP_DASHBOARD_DATA_START = "FETCH_AIRDROP_DASHBOARD_DATA_START";