export const AIRDROP_USER_SUCCESS = "AIRDROP_USER_SUCCESS";
export const AIRDROP_USER_FAIL = "AIRDROP_USER_FAIL";
export const AIRDROP_USER_START = "AIRDROP_USER_START";

export const AIRDROP_ALL_USERS = "AIRDROP_ALL_USERS"

export const FETCH_DASHBOARD_DATA_SUCCESS = "FETCH_DASHBOARD_DATA_SUCCESS";
export const FETCH_DASHBOARD_DATA_FAIL = "FETCH_DASHBOARD_DATA_FAIL";
export const FETCH_DASHBOARD_DATA_START = "FETCH_DASHBOARD_DATA_START";

export const FETCH_AIRDROP_DASHBOARD_DATA_SUCCESS = "FETCH_AIRDROP_DASHBOARD_DATA_SUCCESS";
export const FETCH_AIRDROP_DASHBOARD_DATA_FAIL = "FETCH_AIRDROP_DASHBOARD_DATA_FAIL";
export const FETCH_AIRDROP_DASHBOARD_DATA_START = "FETCH_AIRDROP_DASHBOARD_DATA_START";

export const FETCH_LEDGERS_SUCCESS = "FETCH_LEDGERS_SUCCESS"
export const FETCH_LEDGERS_FAIL = "FETCH_LEDGERS_FAIL"
export const FETCH_LEDGERS_START = "FETCH_LEDGERS_START"

export const FETCH_SPECIFIC_LEDGER_SUCCESS = "FETCH_SPECIFIC_LEDGER_SUCCESS"
export const FETCH_SPECIFIC_LEDGER_FAIL = "FETCH_SPECIFIC_LEDGER_FAIL"
export const FETCH_SPECIFIC_LEDGER_START = "FETCH_SPECIFIC_LEDGER_START"

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS"
export const SEARCH_USERS_FAIL = "SEARCH_USERS_FAIL"
export const SEARCH_USERS_START = "SEARCH_USERS_START"
