//!! Fetch Profiles
export const PROFILE_FETCH_ALL_SUCCESS = 'PROFILE_FETCH_ALL_SUCCESS';
export const PROFILE_FETCH_ALL_FAIL = 'PROFILE_FETCH_ALL_FAIL';
export const PROFILE_FETCH_ALL_START = 'PROFILE_FETCH_ALL_START';

