//!! Fetch profiles
export const PROFILE_FETCH_ALL_SUCCESS = 'PROFILE_FETCH_ALL_SUCCESS';
export const PROFILE_FETCH_ALL_FAIL = 'PROFILE_FETCH_ALL_FAIL';
export const PROFILE_FETCH_ALL_START = 'PROFILE_FETCH_ALL_START';

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';

export const SEARCH_PROFILE_SUCCESS = 'SEARCH_PROFILE_SUCCESS';
export const SEARCH_PROFILE_FAIL = 'SEARCH_PROFILE_FAIL';
export const SEARCH_PROFILE_START = 'SEARCH_PROFILE_START';


//!! Fetch pending profiles (for facebook and youtube screenshots)
export const PROFILE_PENDING_FETCH_SUCCESS = 'PROFILE_PENDING_FETCH_SUCCESS'
export const PROFILE_PENDING_FETCH_FAIL = 'PROFILE_PENDING_FETCH_FAIL'
export const PROFILE_PENDING_FETCH_START = 'PROFILE_PENDING_FETCH_START'

export const PROFILE_VERIFY_SCREENSHOT_SUCCESS = 'PROFILE_VERIFY_SCREENSHOT_SUCCESS';
export const PROFILE_VERIFY_SCREENSHOT_FAIL = 'PROFILE_VERIFY_SCREENSHOT_FAIL';
export const PROFILE_VERIFY_SCREENSHOT_START = 'PROFILE_VERIFY_SCREENSHOT_START';
