//!! Create user (add)
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_START = "CREATE_USER_START";

export const FETCH_GWX_USERS_SUCCESS = "FETCH_GWX_USERS_SUCCESS";
export const FETCH_GWX_USERS_FAIL = "FETCH_GWX_USERS_FAIL";
export const FETCH_GWX_USERS_START = "FETCH_GWX_USERS_START";
