//!! Create user (add)
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_START = "CREATE_USER_START";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_START = "DELETE_USER_START";

export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const SEARCH_USER_START = "SEARCH_USER_START";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const FETCH_USERS_START = "FETCH_USERS_START";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FETCH_USER_START = "FETCH_USER_START";

export const FETCH_GWX_USERS_SUCCESS = "FETCH_GWX_USERS_SUCCESS";
export const FETCH_GWX_USERS_FAIL = "FETCH_GWX_USERS_FAIL";
export const FETCH_GWX_USERS_START = "FETCH_GWX_USERS_START";
